CREATE TABLE IF NOT EXISTS LIVRO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255),
    autor VARCHAR(255),
    ano_publicacao DATE,
    editora VARCHAR(255)
    );

INSERT INTO
    LIVRO (titulo, autor, ano_publicacao, editora)
VALUES
    ('Harry Potter', 'J.K. Rowling', '2020-10-28', 'Colen Silver'),
    ('O Senhor dos Anéis', 'J.R.R. Tolkien', '2019-03-15', 'Middle-earth Press'),
    ('Seu Livro', 'Seu Autor', '2023-11-10', 'Sua Editora'),
    ('O Código Da Vinci', 'Dan Brown', '2018-08-05', 'Conspiracy Books'),
    ('O Hobbit', 'J.R.R. Tolkien', '2015-01-12', 'Middle-earth Press'),
    ('A Menina que Roubava Livros', 'Markus Zusak', '2018-06-23', 'Book Thief Publishing'),
    ('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', '2019-09-19', 'Little Prince Books'),
    ('A Hospedeira', 'Stephenie Meyer', '2020-04-08', 'Alien Invasion Publishing'),
    ('O Nome do Vento', 'Patrick Rothfuss', '2017-11-27', 'Epic Fantasy Books'),
    ('O Poder do Hábito', 'Charles Duhigg', '2021-02-03', 'Self-Help Publications'),
    ('As Crônicas de Nárnia', 'C.S. Lewis', '2016-05-09', 'Fantasy World Press'),
    ('O Iluminado', 'Stephen King', '2018-08-14', 'Horror Novels'),
    ('A Torre Negra', 'Stephen King', '2019-12-25', 'Dark Tower Publishing'),
    ('A Máquina do Tempo', 'H.G. Wells', '2017-03-01', 'Sci-Fi Classics'),
    ('A Metamorfose', 'Franz Kafka', '2020-06-11', 'Existential Literature'),
    ('As Vinhas da Ira', 'John Steinbeck', '2015-09-17', 'Great Depression Books'),
    ('Fahrenheit 451', 'Ray Bradbury', '2018-01-04', 'Dystopian Classics'),
    ('Duna', 'Frank Herbert', '2022-04-30', 'Science Fiction Publishing'),
    ('A Revolta de Atlas', 'Ayn Rand', '2016-09-08', 'Objectivist Press'),
    ('A Arte da Guerra', 'Sun Tzu', '2017-12-20', 'Strategy Books'),
    ('O Príncipe', 'Maquiavel', '2019-05-15', 'Political Classics'),
    ('A Divina Comédia', 'Dante Alighieri', '2021-10-10', 'Epic Poetry Publications'),
    ('Moby Dick', 'Herman Melville', '2015-08-02', 'Whaling Press'),
    ('Orgulho e Preconceito', 'Jane Austen', '2022-05-21', 'Regency Publishers'),
    ('Cem Anos de Solidão', 'Gabriel García Márquez', '2020-02-14', 'Magical Realism Press'),
    ('A Cabana', 'William P. Young', '2016-04-30', 'Faithful Publishing'),
    ('O Retrato de Dorian Gray', 'Oscar Wilde', '2018-11-08', 'Victorian Novels'),
    ('A Odisséia', 'Homero', '2019-04-25', 'Epic Poetry Publications'),
    ('O Senhor das Moscas', 'William Golding', '2017-06-19', 'Allegorical Fiction'),
    ('Drácula', 'Bram Stoker', '2022-08-17', 'Gothic Horror Publishing'),
    ('Crime e Castigo', 'Fiódor Dostoiévski', '2016-07-12', 'Russian Literature Press'),
    ('A Iliada', 'Homero', '2018-03-07', 'Epic Poetry Publications'),
    ('A Revolução dos Bichos', 'George Orwell', '2017-09-18', 'Animal Farm Books'),
    ('A Culpa é das Estrelas', 'John Green', '2019-11-07', 'Sad Love Publications'),
    ('O Grande Gatsby', 'F. Scott Fitzgerald', '2021-06-14', 'Jazz Age Press'),
    ('1984', 'George Orwell', '2021-07-02', 'Dystopian Books'),
    ('Admirável Mundo Novo', 'Aldous Huxley', '2016-12-03', 'Brave New World Publications'),
    ('O Retorno do Rei', 'J.R.R. Tolkien', '2023-02-28', 'Middle-earth Press');
